### ISSUE TITLE
Should all components be in Client or Server project?

### ISSUE THREAD

**Issue by ngcsontrh** [matengo/OptimalBlazorSetup#1]
Hi, I'm very impressed with your project setup. I plan to create a web app using gRPC, similar to your setup, and I’ve created a gRPC service running in a separate project within the same solution. From what I see in your setup, you place almost all pages in the Blazor Client project, while the Server project handles requests to the gRPC service. Should I put all components and pages in the Client project, and use the Server project only for making calls to the gRPC backend?

**Comment by matengo** [comment]
Hi, thank you.
This is just the standard Blazor Web App template but configured with Magic Onion. Magic Onion is a Grpc framework, so you don't need a separate Grpc backend. In this case the serverpart of the web app template is a Grpc Service/Grpc backend. I prefer to be able to have pages and components to be interactive clientside in the browser, so I put them in the client project. Then they (the components and pages) can be executed serverside AND clientside. And when you use Magic Onion, you don't have to think of where they are executed, if they are executed serverside or clientside. When they are executed serverside the call to a service is done locally as any standard C# code, when they are executed clientside Magic Onion do a Grpc request to the service. So it's a very good setup for handling all the different rendermodes, because the components can be executed anywhere without any component changes or duplication of code. A bonus is that Grpc with Memorypack is very efficient and fast, much faster than a normal Json rest api.
